stages:
  - stage0
  - stage1
  - stage2

.odinllmTemplate:
  image: git.ordbogen.com:5050/odin/odinllm/odinllm
  when: on_success
  allow_failure: false
  tags:
    - odin
  before_script:
    - source /root/.bashrc
    - conda activate env
    - export WANDB_MODE=disabled

.gpu:
  zero:
    - export CUDA_VISIBLE_DEVICES=
  one:
    - export CUDA_VISIBLE_DEVICES=$(while ! scripts/cuda.sh 1; do sleep 1; done)
  two:
    - export CUDA_VISIBLE_DEVICES=$(while ! scripts/cuda.sh 2; do sleep 1; done)

.stage0Template:
  extends: .odinllmTemplate
  stage: stage0

init:
  extends: .stage0Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm init config/default.yaml config/models/tiny.yaml models/test
  artifacts:
    paths:
      - models/test

snapshot:
  extends: .stage0Template
  script:
    - !reference [.gpu, zero]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - CUDA_VISIBLE_DEVICES= python -m odinllm snapshot config/default.yaml peter-sk/gpt-neox-da-tiny --target-dir models/neox
  artifacts:
    paths:
      - models/neox

.stage1Template:
  extends: .odinllmTemplate
  stage: stage1

eval:
  extends: .stage1Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm eval config/default.yaml config/eval/sft-1000.yaml models/test
    - python -m odinllm eval config/default.yaml config/eval/sft-1000.yaml models/neox
  needs:
    - init
    - snapshot

sft:
  extends: .stage1Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm train config/default.yaml config/train/sft-1000.yaml models/test models/test-sft
  needs:
    - init
  artifacts:
    paths:
      - models/test-sft

pretrain:
  extends: .stage1Template
  script:
    - !reference [.gpu, two]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - NCCL_P2P_DISABLE=1 NCCL_IB_DISABLE=1 NCCL_SOCKET_IFNAME=lo NCCL_P2P_LEVEL=LOC ACCELERATE_LOG_LEVEL=info accelerate launch --main_process_port=29501 --config_file config/accelerate/multi_gpu.yaml --num_processes=2 -m odinllm train config/default.yaml config/train/pretrain-1000.yaml models/test models/test-pretrain
  needs:
    - init
  artifacts:
    paths:
      - models/test-pretrain

quantize:
  extends: .stage1Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm quantize config/default.yaml config/train/sft-1000.yaml models/test models/test-gptq
  needs:
    - init
  artifacts:
    paths:
      - models/test-gptq

edit:
  extends: .stage1Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm edit config/default.yaml config/train/sft-1000.yaml models/neox models/neox-expanded --layers gpt_neox.layers --zero attention.dense --zero mlp.dense_4h_to_h --add-every 4
  needs:
    - snapshot
  artifacts:
    paths:
      - models/neox-expanded

.stage2Template:
  extends: .odinllmTemplate
  stage: stage2

finalize:
  extends: .stage2Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm finalize config/default.yaml config/train/sft-1000.yaml models/test-sft --base-model models/test
  needs:
    - init
    - sft

infer:
  extends: .stage2Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm infer config/default.yaml config/train/sft-1000.yaml models/test --lora-adapter models/test-sft
    - python -m odinllm infer config/default.yaml config/train/sft-1000.yaml models/neox
  needs:
    - init
    - sft
    - snapshot

merge:
  extends: .stage2Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm merge config/default.yaml config/train/sft-1000.yaml models/test models/test-sft models/test-merged
  needs:
    - init
    - sft
  artifacts:
    paths:
      - models/test-merged

launch:
  extends: .stage2Template
  script:
    - !reference [.gpu, one]
    - echo "CUDA_VISIBLE_DEVICES='$CUDA_VISIBLE_DEVICES'"
    - python -m odinllm launch models/neox-expanded/metadata.yaml
  needs:
    - edit
