model:
  torch_dtype: ::torch.bfloat16
  use_flash_attention_2: false
train:
  peft: false
#  instruction_template: "\n\nInstruction:\n"
#  response_template: "\n\nResponse:\n"
training_args:
  per_device_eval_batch_size: 16
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  bf16: true
  report_to: wandb
  save_strategy: "no"
  load_best_model_at_end: false
  gradient_checkpointing: false
trainer_args:
#  max_seq_length: 2048
  packing: true
datasets:
  train_datasets:
    - split: "train"
      shuffle: true
      name: "data/Vicuna.da.json"
      infinite: true
      from: 100
    - split: "train"
      shuffle: true
      name: "data/alpaca_gpt4_data.da.json"
      infinite: true
      from: 100
    - split: "train"
      shuffle: true
      name: "data/gpteacher-da.json"
      infinite: true
      from: 100
    - split: "train"
      shuffle: true
      name: "data/guanaco_additional-da.json"
      infinite: true
      from: 100
    - split: "train"
      shuffle: true
      name: "data/hc3-chatgpt-da.json"
      infinite: true
      from: 100
  eval_datasets:
    - split: "train"
      shuffle: true
      name: "data/Vicuna.da.json"
      infinite: false
      to: 1000
    - split: "train"
      shuffle: true
      name: "data/alpaca_gpt4_data.da.json"
      infinite: false
      to: 100
    - split: "train"
      shuffle: true
      name: "data/gpteacher-da.json"
      infinite: false
      to: 100
    - split: "train"
      shuffle: true
      name: "data/guanaco_additional-da.json"
      infinite: false
      to: 100
    - split: "train"
      shuffle: true
      name: "data/hc3-chatgpt-da.json"
      infinite: false
      to: 100
