model:
  torch_dtype: ::torch.float16
#  attn_implementation: null
  use_flash_attention_2: false
training_args:
  per_device_eval_batch_size: 1
  per_device_train_batch_size: 1
  bf16: false
  fp16: false
  report_to: null
datasets:
  train_datasets:
    - split: "train"
      shuffle: true
      name: "data/alpaca-da-1000.jsonl"
      infinite: true
  eval_datasets:
    - split: "train"
      shuffle: true
      name: "data/Vicuna-da-1000.jsonl"
      infinite: false
  quantize_datasets:
    - split: "train"
      shuffle: true
      name: "data/alpaca-da-1000.jsonl"
      infinite: false
    - split: "train"
      shuffle: true
      name: "data/Vicuna-da-1000.jsonl"
      infinite: false
