model:
  torch_dtype: ::torch.float32
#  attn_implementation: null
  use_flash_attention_2: false
training_args:
  output_dir: "output"
  per_device_eval_batch_size: 1
  bf16: false
  report_to: null
datasets:
  eval_datasets:
    - split: "train"
      shuffle: true
      name: "data/alpaca-da-1000.jsonl"
      infinite: false
    - split: "train"
      shuffle: true
      name: "data/Vicuna-da-1000.jsonl"
      infinite: false
